tp @a[tag=TeleportHub] 20 -59 179 90 0
tag @a remove InGame
tag @a remove OnAKIRequest
tag @a remove "00"
tag @a remove "01"
tag @a remove "02"
tag @a remove "03"
tag @a remove "04"
tag @a remove "05"
tag @a remove "06"
tag @a remove "07"
tag @a remove "08"
tag @a remove "09"
tag @a remove "10"
tag @a remove "11"
tag @a remove "12"
tag @a remove "13"
tag @a remove "14"
tag @a remove "15"
tag @a remove "16"
tag @a remove "17"
tag @a remove "18"
tag @a remove "19"
tag @a remove "20"
tag @a remove "21"
tag @a remove "22"
tag @a remove "23"
tag @a remove "24"
tag @a remove "25"
tag @a remove "26"
tag @a remove "27"
tag @a remove "28"
tag @a remove "29"
tag @a remove "30"
tag @a remove "31"
tag @a remove "32"
tag @a remove "33"
tag @a remove "34"
tag @a remove "35"
tag @a remove "36"
tag @a remove "37"
tag @a remove "38"
tag @a remove "39"
tag @a remove "40"
tag @a remove "41"
tag @a remove "42"
tag @a remove "43"
tag @a remove "44"
tag @a remove "45"
tag @a remove "46"
tag @a remove "47"
tag @a remove "48"
tag @a remove "49"
tag @a remove "50"
tag @a remove "51"
tag @a remove "52"
tag @a remove "53"
tag @a remove "54"
tag @a remove "55"
tag @a remove "56"
tag @a remove "57"
tag @a remove "58"
tag @a remove "59"
tag @a remove "60"
tag @a remove "61"
tag @a remove "62"
tag @a remove "63"
tag @a remove "64"
tag @a remove "65"
tag @a remove "66"
tag @a remove "67"
tag @a remove "68"
tag @a remove "69"
tag @a remove "70"
tag @a remove "71"
tag @a remove "72"
tag @a remove "73"
tag @a remove "74"
tag @a remove "75"
tag @a remove "76"
tag @a remove "77"
tag @a remove "78"
tag @a remove "79"
tag @a remove "80"
tag @a remove "81"
tag @a remove "82"
tag @a remove "83"
tag @a remove "84"
tag @a remove "85"
tag @a remove "86"
tag @a remove "87"
tag @a remove "88"
tag @a remove "89"
tag @a remove "90"
tag @a remove "91"
tag @a remove "92"
tag @a remove "93"
tag @a remove "94"
tag @a remove "95"
tag @a remove "96"
tag @a remove "97"
tag @a remove "98"
tag @a remove "99"
tag @a remove TeleportHub
tag @a remove requestor
title @a clear
title @a reset
kill @e[type=informant:timebar]
kill @e[type=item]
inputpermission set @a camera enabled
inputpermission set @a movement enabled
clear @a[tag=InGame]
tag @a remove blue_orange
tag @a remove blue_white
tag @a remove red_cyan
tag @a remove green_red
tag @a remove green_yellow
tag @a remove orange_white
tag @a remove blue_pink
tag @a remove pink_green
tag @a remove purple_cyan
tag @a remove purple_green
tag @a remove purple_yellow
tag @a remove red_white
tag @a remove white_purple
tag @a remove yellow_cyan
tag @a remove red_purple
tag @a remove red_team
tag @a remove blue_team
tag @a remove red_green
tag @a remove red_yellow
tag @a remove red_red
tag @a remove red_gray
tag @a remove red_black
tag @a remove red_lemon
tag @a remove red_lime
tag @a remove red_pink
tag @a remove blue_yellow
tag @a remove blue_blue
tag @a remove blue_purple
tag @a remove blue_green
tag @a remove blue_gray
tag @a remove blue_black
tag @a remove blue_lemon
tag @a remove blue_lime
tag @a remove blue_cyan
tag @a remove red_rose
tag @a remove blue_sky
tag @a remove green_white
tag @a remove green_green
tag @a remove green_gray
tag @a remove green_black
tag @a remove green_lime
tag @a remove yellow_white
tag @a remove yellow_black
tag @a remove yellow_gray
tag @a remove yellow_lemon
tag @a remove yellow_yellow
tag @a remove red_team
tag @a remove blue_team
tag @a remove green_team
tag @a remove yellow_team
damage @a 0 entity_attack
tag @a remove winner