camera @a[tag=InGame,tag=!spectator] set minecraft:first_person
clear @a[tag=InGame]
execute as @a at @s if block ~ ~-3 ~ informant:start run gamemode a @s
execute as @a at @s if block ~ ~-4 ~ informant:start run gamemode a @s
execute as @a at @s if block ~ ~-3 ~ honey_block run gamemode a @s
execute as @a at @s if block ~ ~-4 ~ honey_block run gamemode a @s
execute as @a at @s if block ~ ~-3 ~ diamond_ore run gamemode a @s
execute as @a at @s if block ~ ~-4 ~ diamond_ore run gamemode a @s
execute as @a at @s if block ~ ~-3 ~ dried_kelp_block run gamemode a @s
execute as @a at @s if block ~ ~-4 ~ dried_kelp_block run gamemode a @s
execute as @a at @s if block ~ ~-3 ~ fletching_table run gamemode a @s
execute as @a at @s if block ~ ~-4 ~ fletching_table run gamemode a @s
replaceitem entity @a[tag=InGame,tag=!spectator] slot.hotbar 0 informant:phone 1 0 {"item_lock": { "mode": "lock_in_slot" } }
replaceitem entity @a[tag=InGame,tag=!spectator] slot.hotbar 1 spyglass 1 0 {"item_lock": { "mode": "lock_in_slot"}}
replaceitem entity @a[tag=InGame,tag=!spectator] slot.hotbar 8 informant:give_up 1 0 {"item_lock": { "mode": "lock_in_slot"}}
tag @a remove GameOver
execute if score player1 teleport_r > player2 teleport_r run scoreboard players add player1 teleport_point 1
execute if score player1 teleport_r > player3 teleport_r run scoreboard players add player1 teleport_point 1
execute if score player1 teleport_r > player4 teleport_r run scoreboard players add player1 teleport_point 1
execute if score player1 teleport_r > player5 teleport_r run scoreboard players add player1 teleport_point 1
execute if score player1 teleport_r > player6 teleport_r run scoreboard players add player1 teleport_point 1
execute if score player1 teleport_r > player7 teleport_r run scoreboard players add player1 teleport_point 1
execute if score player1 teleport_r > player8 teleport_r run scoreboard players add player1 teleport_point 1
execute if score player1 teleport_r > player9 teleport_r run scoreboard players add player1 teleport_point 1
execute if score player1 teleport_r > player10 teleport_r run scoreboard players add player1 teleport_point 1
execute if score player1 teleport_r > player11 teleport_r run scoreboard players add player1 teleport_point 1
execute if score player1 teleport_r > player12 teleport_r run scoreboard players add player1 teleport_point 1
execute if score player1 teleport_r > player13 teleport_r run scoreboard players add player1 teleport_point 1
execute if score player1 teleport_r > player14 teleport_r run scoreboard players add player1 teleport_point 1
execute if score player1 teleport_r > player15 teleport_r run scoreboard players add player1 teleport_point 1
execute if score player2 teleport_r > player1 teleport_r run scoreboard players add player2 teleport_point 1
execute if score player2 teleport_r > player3 teleport_r run scoreboard players add player2 teleport_point 1
execute if score player2 teleport_r > player4 teleport_r run scoreboard players add player2 teleport_point 1
execute if score player2 teleport_r > player5 teleport_r run scoreboard players add player2 teleport_point 1
execute if score player2 teleport_r > player6 teleport_r run scoreboard players add player2 teleport_point 1
execute if score player2 teleport_r > player7 teleport_r run scoreboard players add player2 teleport_point 1
execute if score player2 teleport_r > player8 teleport_r run scoreboard players add player2 teleport_point 1
execute if score player2 teleport_r > player9 teleport_r run scoreboard players add player2 teleport_point 1
execute if score player2 teleport_r > player10 teleport_r run scoreboard players add player2 teleport_point 1
execute if score player2 teleport_r > player11 teleport_r run scoreboard players add player2 teleport_point 1
execute if score player2 teleport_r > player12 teleport_r run scoreboard players add player2 teleport_point 1
execute if score player2 teleport_r > player13 teleport_r run scoreboard players add player2 teleport_point 1
execute if score player2 teleport_r > player14 teleport_r run scoreboard players add player2 teleport_point 1
execute if score player2 teleport_r > player15 teleport_r run scoreboard players add player2 teleport_point 1
execute if score player3 teleport_r > player1 teleport_r run scoreboard players add player3 teleport_point 1
execute if score player3 teleport_r > player2 teleport_r run scoreboard players add player3 teleport_point 1
execute if score player3 teleport_r > player4 teleport_r run scoreboard players add player3 teleport_point 1
execute if score player3 teleport_r > player5 teleport_r run scoreboard players add player3 teleport_point 1
execute if score player3 teleport_r > player6 teleport_r run scoreboard players add player3 teleport_point 1
execute if score player3 teleport_r > player7 teleport_r run scoreboard players add player3 teleport_point 1
execute if score player3 teleport_r > player8 teleport_r run scoreboard players add player3 teleport_point 1
execute if score player3 teleport_r > player9 teleport_r run scoreboard players add player3 teleport_point 1
execute if score player3 teleport_r > player10 teleport_r run scoreboard players add player3 teleport_point 1
execute if score player3 teleport_r > player11 teleport_r run scoreboard players add player3 teleport_point 1
execute if score player3 teleport_r > player12 teleport_r run scoreboard players add player3 teleport_point 1
execute if score player3 teleport_r > player13 teleport_r run scoreboard players add player3 teleport_point 1
execute if score player3 teleport_r > player14 teleport_r run scoreboard players add player3 teleport_point 1
execute if score player3 teleport_r > player15 teleport_r run scoreboard players add player3 teleport_point 1
execute if score player4 teleport_r > player1 teleport_r run scoreboard players add player4 teleport_point 1
execute if score player4 teleport_r > player2 teleport_r run scoreboard players add player4 teleport_point 1
execute if score player4 teleport_r > player3 teleport_r run scoreboard players add player4 teleport_point 1
execute if score player4 teleport_r > player5 teleport_r run scoreboard players add player4 teleport_point 1
execute if score player4 teleport_r > player6 teleport_r run scoreboard players add player4 teleport_point 1
execute if score player4 teleport_r > player7 teleport_r run scoreboard players add player4 teleport_point 1
execute if score player4 teleport_r > player8 teleport_r run scoreboard players add player4 teleport_point 1
execute if score player4 teleport_r > player9 teleport_r run scoreboard players add player4 teleport_point 1
execute if score player4 teleport_r > player10 teleport_r run scoreboard players add player4 teleport_point 1
execute if score player4 teleport_r > player11 teleport_r run scoreboard players add player4 teleport_point 1
execute if score player4 teleport_r > player12 teleport_r run scoreboard players add player4 teleport_point 1
execute if score player4 teleport_r > player13 teleport_r run scoreboard players add player4 teleport_point 1
execute if score player4 teleport_r > player14 teleport_r run scoreboard players add player4 teleport_point 1
execute if score player4 teleport_r > player15 teleport_r run scoreboard players add player4 teleport_point 1
execute if score player5 teleport_r > player1 teleport_r run scoreboard players add player5 teleport_point 1
execute if score player5 teleport_r > player2 teleport_r run scoreboard players add player5 teleport_point 1
execute if score player5 teleport_r > player3 teleport_r run scoreboard players add player5 teleport_point 1
execute if score player5 teleport_r > player4 teleport_r run scoreboard players add player5 teleport_point 1
execute if score player5 teleport_r > player6 teleport_r run scoreboard players add player5 teleport_point 1
execute if score player5 teleport_r > player7 teleport_r run scoreboard players add player5 teleport_point 1
execute if score player5 teleport_r > player8 teleport_r run scoreboard players add player5 teleport_point 1
execute if score player5 teleport_r > player9 teleport_r run scoreboard players add player5 teleport_point 1
execute if score player5 teleport_r > player10 teleport_r run scoreboard players add player5 teleport_point 1
execute if score player5 teleport_r > player11 teleport_r run scoreboard players add player5 teleport_point 1
execute if score player5 teleport_r > player12 teleport_r run scoreboard players add player5 teleport_point 1
execute if score player5 teleport_r > player13 teleport_r run scoreboard players add player5 teleport_point 1
execute if score player5 teleport_r > player14 teleport_r run scoreboard players add player5 teleport_point 1
execute if score player5 teleport_r > player15 teleport_r run scoreboard players add player5 teleport_point 1
execute if score player6 teleport_r > player1 teleport_r run scoreboard players add player6 teleport_point 1
execute if score player6 teleport_r > player2 teleport_r run scoreboard players add player6 teleport_point 1
execute if score player6 teleport_r > player3 teleport_r run scoreboard players add player6 teleport_point 1
execute if score player6 teleport_r > player4 teleport_r run scoreboard players add player6 teleport_point 1
execute if score player6 teleport_r > player5 teleport_r run scoreboard players add player6 teleport_point 1
execute if score player6 teleport_r > player7 teleport_r run scoreboard players add player6 teleport_point 1
execute if score player6 teleport_r > player8 teleport_r run scoreboard players add player6 teleport_point 1
execute if score player6 teleport_r > player9 teleport_r run scoreboard players add player6 teleport_point 1
execute if score player6 teleport_r > player10 teleport_r run scoreboard players add player6 teleport_point 1
execute if score player6 teleport_r > player11 teleport_r run scoreboard players add player6 teleport_point 1
execute if score player6 teleport_r > player12 teleport_r run scoreboard players add player6 teleport_point 1
execute if score player6 teleport_r > player13 teleport_r run scoreboard players add player6 teleport_point 1
execute if score player6 teleport_r > player14 teleport_r run scoreboard players add player6 teleport_point 1
execute if score player6 teleport_r > player15 teleport_r run scoreboard players add player6 teleport_point 1
execute if score player7 teleport_r > player1 teleport_r run scoreboard players add player7 teleport_point 1
execute if score player7 teleport_r > player2 teleport_r run scoreboard players add player7 teleport_point 1
execute if score player7 teleport_r > player3 teleport_r run scoreboard players add player7 teleport_point 1
execute if score player7 teleport_r > player4 teleport_r run scoreboard players add player7 teleport_point 1
execute if score player7 teleport_r > player5 teleport_r run scoreboard players add player7 teleport_point 1
execute if score player7 teleport_r > player6 teleport_r run scoreboard players add player7 teleport_point 1
execute if score player7 teleport_r > player8 teleport_r run scoreboard players add player7 teleport_point 1
execute if score player7 teleport_r > player9 teleport_r run scoreboard players add player7 teleport_point 1
execute if score player7 teleport_r > player10 teleport_r run scoreboard players add player7 teleport_point 1
execute if score player7 teleport_r > player11 teleport_r run scoreboard players add player7 teleport_point 1
execute if score player7 teleport_r > player12 teleport_r run scoreboard players add player7 teleport_point 1
execute if score player7 teleport_r > player13 teleport_r run scoreboard players add player7 teleport_point 1
execute if score player7 teleport_r > player14 teleport_r run scoreboard players add player7 teleport_point 1
execute if score player7 teleport_r > player15 teleport_r run scoreboard players add player7 teleport_point 1
execute if score player8 teleport_r > player1 teleport_r run scoreboard players add player8 teleport_point 1
execute if score player8 teleport_r > player2 teleport_r run scoreboard players add player8 teleport_point 1
execute if score player8 teleport_r > player3 teleport_r run scoreboard players add player8 teleport_point 1
execute if score player8 teleport_r > player4 teleport_r run scoreboard players add player8 teleport_point 1
execute if score player8 teleport_r > player5 teleport_r run scoreboard players add player8 teleport_point 1
execute if score player8 teleport_r > player6 teleport_r run scoreboard players add player8 teleport_point 1
execute if score player8 teleport_r > player7 teleport_r run scoreboard players add player8 teleport_point 1
execute if score player8 teleport_r > player9 teleport_r run scoreboard players add player8 teleport_point 1
execute if score player8 teleport_r > player10 teleport_r run scoreboard players add player8 teleport_point 1
execute if score player8 teleport_r > player11 teleport_r run scoreboard players add player8 teleport_point 1
execute if score player8 teleport_r > player12 teleport_r run scoreboard players add player8 teleport_point 1
execute if score player8 teleport_r > player13 teleport_r run scoreboard players add player8 teleport_point 1
execute if score player8 teleport_r > player14 teleport_r run scoreboard players add player8 teleport_point 1
execute if score player8 teleport_r > player15 teleport_r run scoreboard players add player8 teleport_point 1
execute if score player9 teleport_r > player1 teleport_r run scoreboard players add player9 teleport_point 1
execute if score player9 teleport_r > player2 teleport_r run scoreboard players add player9 teleport_point 1
execute if score player9 teleport_r > player3 teleport_r run scoreboard players add player9 teleport_point 1
execute if score player9 teleport_r > player4 teleport_r run scoreboard players add player9 teleport_point 1
execute if score player9 teleport_r > player5 teleport_r run scoreboard players add player9 teleport_point 1
execute if score player9 teleport_r > player6 teleport_r run scoreboard players add player9 teleport_point 1
execute if score player9 teleport_r > player7 teleport_r run scoreboard players add player9 teleport_point 1
execute if score player9 teleport_r > player8 teleport_r run scoreboard players add player9 teleport_point 1
execute if score player9 teleport_r > player10 teleport_r run scoreboard players add player9 teleport_point 1
execute if score player9 teleport_r > player11 teleport_r run scoreboard players add player9 teleport_point 1
execute if score player9 teleport_r > player12 teleport_r run scoreboard players add player9 teleport_point 1
execute if score player9 teleport_r > player13 teleport_r run scoreboard players add player9 teleport_point 1
execute if score player9 teleport_r > player14 teleport_r run scoreboard players add player9 teleport_point 1
execute if score player9 teleport_r > player15 teleport_r run scoreboard players add player9 teleport_point 1
execute if score player10 teleport_r > player1 teleport_r run scoreboard players add player10 teleport_point 1
execute if score player10 teleport_r > player2 teleport_r run scoreboard players add player10 teleport_point 1
execute if score player10 teleport_r > player3 teleport_r run scoreboard players add player10 teleport_point 1
execute if score player10 teleport_r > player4 teleport_r run scoreboard players add player10 teleport_point 1
execute if score player10 teleport_r > player5 teleport_r run scoreboard players add player10 teleport_point 1
execute if score player10 teleport_r > player6 teleport_r run scoreboard players add player10 teleport_point 1
execute if score player10 teleport_r > player7 teleport_r run scoreboard players add player10 teleport_point 1
execute if score player10 teleport_r > player8 teleport_r run scoreboard players add player10 teleport_point 1
execute if score player10 teleport_r > player9 teleport_r run scoreboard players add player10 teleport_point 1
execute if score player10 teleport_r > player11 teleport_r run scoreboard players add player10 teleport_point 1
execute if score player10 teleport_r > player12 teleport_r run scoreboard players add player10 teleport_point 1
execute if score player10 teleport_r > player13 teleport_r run scoreboard players add player10 teleport_point 1
execute if score player10 teleport_r > player14 teleport_r run scoreboard players add player10 teleport_point 1
execute if score player10 teleport_r > player15 teleport_r run scoreboard players add player10 teleport_point 1
execute if score player11 teleport_r > player1 teleport_r run scoreboard players add player11 teleport_point 1
execute if score player11 teleport_r > player2 teleport_r run scoreboard players add player11 teleport_point 1
execute if score player11 teleport_r > player3 teleport_r run scoreboard players add player11 teleport_point 1
execute if score player11 teleport_r > player4 teleport_r run scoreboard players add player11 teleport_point 1
execute if score player11 teleport_r > player5 teleport_r run scoreboard players add player11 teleport_point 1
execute if score player11 teleport_r > player6 teleport_r run scoreboard players add player11 teleport_point 1
execute if score player11 teleport_r > player7 teleport_r run scoreboard players add player11 teleport_point 1
execute if score player11 teleport_r > player8 teleport_r run scoreboard players add player11 teleport_point 1
execute if score player11 teleport_r > player9 teleport_r run scoreboard players add player11 teleport_point 1
execute if score player11 teleport_r > player10 teleport_r run scoreboard players add player11 teleport_point 1
execute if score player11 teleport_r > player12 teleport_r run scoreboard players add player11 teleport_point 1
execute if score player11 teleport_r > player13 teleport_r run scoreboard players add player11 teleport_point 1
execute if score player11 teleport_r > player14 teleport_r run scoreboard players add player11 teleport_point 1
execute if score player11 teleport_r > player15 teleport_r run scoreboard players add player11 teleport_point 1
execute if score player12 teleport_r > player1 teleport_r run scoreboard players add player12 teleport_point 1
execute if score player12 teleport_r > player2 teleport_r run scoreboard players add player12 teleport_point 1
execute if score player12 teleport_r > player3 teleport_r run scoreboard players add player12 teleport_point 1
execute if score player12 teleport_r > player4 teleport_r run scoreboard players add player12 teleport_point 1
execute if score player12 teleport_r > player5 teleport_r run scoreboard players add player12 teleport_point 1
execute if score player12 teleport_r > player6 teleport_r run scoreboard players add player12 teleport_point 1
execute if score player12 teleport_r > player7 teleport_r run scoreboard players add player12 teleport_point 1
execute if score player12 teleport_r > player8 teleport_r run scoreboard players add player12 teleport_point 1
execute if score player12 teleport_r > player9 teleport_r run scoreboard players add player12 teleport_point 1
execute if score player12 teleport_r > player10 teleport_r run scoreboard players add player12 teleport_point 1
execute if score player12 teleport_r > player11 teleport_r run scoreboard players add player12 teleport_point 1
execute if score player12 teleport_r > player13 teleport_r run scoreboard players add player12 teleport_point 1
execute if score player12 teleport_r > player14 teleport_r run scoreboard players add player12 teleport_point 1
execute if score player12 teleport_r > player15 teleport_r run scoreboard players add player12 teleport_point 1
execute if score player13 teleport_r > player1 teleport_r run scoreboard players add player13 teleport_point 1
execute if score player13 teleport_r > player2 teleport_r run scoreboard players add player13 teleport_point 1
execute if score player13 teleport_r > player3 teleport_r run scoreboard players add player13 teleport_point 1
execute if score player13 teleport_r > player4 teleport_r run scoreboard players add player13 teleport_point 1
execute if score player13 teleport_r > player5 teleport_r run scoreboard players add player13 teleport_point 1
execute if score player13 teleport_r > player6 teleport_r run scoreboard players add player13 teleport_point 1
execute if score player13 teleport_r > player7 teleport_r run scoreboard players add player13 teleport_point 1
execute if score player13 teleport_r > player8 teleport_r run scoreboard players add player13 teleport_point 1
execute if score player13 teleport_r > player9 teleport_r run scoreboard players add player13 teleport_point 1
execute if score player13 teleport_r > player10 teleport_r run scoreboard players add player13 teleport_point 1
execute if score player13 teleport_r > player11 teleport_r run scoreboard players add player13 teleport_point 1
execute if score player13 teleport_r > player12 teleport_r run scoreboard players add player13 teleport_point 1
execute if score player13 teleport_r > player14 teleport_r run scoreboard players add player13 teleport_point 1
execute if score player13 teleport_r > player15 teleport_r run scoreboard players add player13 teleport_point 1
execute if score player14 teleport_r > player1 teleport_r run scoreboard players add player14 teleport_point 1
execute if score player14 teleport_r > player2 teleport_r run scoreboard players add player14 teleport_point 1
execute if score player14 teleport_r > player3 teleport_r run scoreboard players add player14 teleport_point 1
execute if score player14 teleport_r > player4 teleport_r run scoreboard players add player14 teleport_point 1
execute if score player14 teleport_r > player5 teleport_r run scoreboard players add player14 teleport_point 1
execute if score player14 teleport_r > player6 teleport_r run scoreboard players add player14 teleport_point 1
execute if score player14 teleport_r > player7 teleport_r run scoreboard players add player14 teleport_point 1
execute if score player14 teleport_r > player8 teleport_r run scoreboard players add player14 teleport_point 1
execute if score player14 teleport_r > player9 teleport_r run scoreboard players add player14 teleport_point 1
execute if score player14 teleport_r > player10 teleport_r run scoreboard players add player14 teleport_point 1
execute if score player14 teleport_r > player11 teleport_r run scoreboard players add player14 teleport_point 1
execute if score player14 teleport_r > player12 teleport_r run scoreboard players add player14 teleport_point 1
execute if score player14 teleport_r > player13 teleport_r run scoreboard players add player14 teleport_point 1
execute if score player14 teleport_r > player15 teleport_r run scoreboard players add player14 teleport_point 1
execute if score player15 teleport_r > player1 teleport_r run scoreboard players add player15 teleport_point 1
execute if score player15 teleport_r > player2 teleport_r run scoreboard players add player15 teleport_point 1
execute if score player15 teleport_r > player3 teleport_r run scoreboard players add player15 teleport_point 1
execute if score player15 teleport_r > player4 teleport_r run scoreboard players add player15 teleport_point 1
execute if score player15 teleport_r > player5 teleport_r run scoreboard players add player15 teleport_point 1
execute if score player15 teleport_r > player6 teleport_r run scoreboard players add player15 teleport_point 1
execute if score player15 teleport_r > player7 teleport_r run scoreboard players add player15 teleport_point 1
execute if score player15 teleport_r > player8 teleport_r run scoreboard players add player15 teleport_point 1
execute if score player15 teleport_r > player9 teleport_r run scoreboard players add player15 teleport_point 1
execute if score player15 teleport_r > player10 teleport_r run scoreboard players add player15 teleport_point 1
execute if score player15 teleport_r > player11 teleport_r run scoreboard players add player15 teleport_point 1
execute if score player15 teleport_r > player12 teleport_r run scoreboard players add player15 teleport_point 1
execute if score player15 teleport_r > player13 teleport_r run scoreboard players add player15 teleport_point 1
execute if score player15 teleport_r > player14 teleport_r run scoreboard players add player15 teleport_point 1
title @a subtitle §o§l§eＳ Ｔ Ａ Ｒ Ｔ
title @a title §c§l密告中
function setNumber
tag @a add NowGame
scoreboard players set timer minutes 30
scoreboard players set timer seconds 0
function teleport